package enums;

public enum ErrorNotification {
	ERRORFOUND, NEW_WORD, CONTINUE, QUIT, PATH, ADD, RENAME_BEFORE, DELETE_BEFORE, RENAME_CURRENT, DELETE_CURRENT, RENAME_AFTER, DELETE_AFTER, UPDATE, INIT, READY, RERUN, NOERRORFOUND, NAMEEXCEPTION, SMALLEXCEPTION, EXCEPTION, FORMATEXCEPTION
}
